export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';
export const TYPING_TITLE = 'TYPING_TITLE';
export const SAVE_TEXT = 'SAVE_TEXT';
export const NEW_AREA = 'NEW_AREA';
export const RESET_AREAS = 'RESET_AREAS';
export const CREATE_CODE_REQUEST = 'CREATE_CODE_REQUEST';
export const CREATE_CODE_SUCCESS = 'CREATE_CODE_SUCCESS';
export const CREATE_CODE_FAILURE = 'CREATE_CODE_FAILURE';
export const REMOVE_CODE_SUCCESS = 'REMOVE_CODE_SUCCESS';
export const REMOVE_CODE_REQUEST = 'REMOVE_CODE_REQUEST';
export const REMOVE_CODE_FAILURE = 'REMOVE_CODE_FAILURE';
export const GET_DOC_REQUEST = 'GET_DOC_REQUEST';
export const GET_DOC_SUCCESS = 'GET_DOC_SUCCESS';
export const GET_DOC_FAILURE = 'GET_DOC_FAILURE';
export const LOAD_DOCUMENTATION = 'LOAD_DOCUMENTATION';
export const EDIT_DOCUMENTATION = 'EDIT_DOCUMENTATION';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const TOGGLE_NAV = 'TOGGLE_NAV';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
